export const formModel = [
	{
		prop:'time1',
		elemType:'datetimerange',
		width:217,
		label:'练考时间'
	},
	{
		prop:'time2',
		width:217,
		elemType:'datetimerange',
		label:'申请时间'
	},
	{
		elemType:'select',
		label:'退费状态',
		prop:'city',
		defaultValue:'',
		col:'label',
		colVal:'value',
		options:[
			{label:'未审核',value:0},
			{label:'审核中',value:1},
			{label:'已退费',value:2},
			{label:'已拒绝',value:3},
			{label:'已关闭',value:4}
		]
	},
	{
		elemType:'select',
		label:'练习车型',
		prop:'carType',
		defaultValue:'',
		col:'label',
		colVal:'value',
		options:[
			{label:'A1',value:'A1'},
			{label:'A2',value:'A2'},
			{label:'C1',value:'C1'}
		]
	},
	{
		group:true,
		label:'高级搜索',
		elemType:'group',
		childs:[
			{
				elemType:'select',
				label:'请选择......',
				prop:'searchType',
				defaultValue:'',
				width:109,
				col:'label',
				colVal:'value',
				options:[
					{label:'教练名称',value:'all'},
					{label:'教练电话',value:'inner'},
					{label:'练考车牌',value:'other'}
				]
			},
			{
				elemType:'input',
				label:'请输入......',
				prop:'content',
				width:109,
				defaultValue:''
			}
		]
	}
]


export const tableModel = [
	{
		type:'selection',
		width:50
	},{
		type:'index',
		width:50
	},{
		prop:'createdTime',
		label:'退费申请时间',
		width:180
	},{
		prop:'signUpTime',
		label:'练考时间',
		width:180
	},{
		prop:'carId',
		label:'练考车牌',
		width:150
	},{
		prop:'subject',
		label:'练考科目'
	},{
		prop:'model',
		label:'练考车型'
	},{
		prop:'coachName',
		label:'教练姓名'
	},{
		prop:'school',
		label:'所属驾校'
	},{
		prop:'duration',
		label:'预约时长'
	},{
		prop:'coachPhone',
		label:'教练电话',
		width:120
	},{
		prop:'discount',
		label:'可获优惠'
	},{
		prop:'isDelay',
		label:'是否顺延',
		width:120,
		formatter:function(row,col,colVal){
			return colVal == 'y'?'是':'否'
		}
	},{
		prop:'orderAmt',
		label:'订单金额(元)',
		width:120
	},{
		prop:'payAmt',
		label:'支付金额(元)',
		width:120
	},{
		prop:'refundAmt',
		label:'退费金额(元)',
		width:120
	},{
		prop:'state',
		label:'审核状态'
	},{
		prop:'reason',
		label:'退费原因'
	},{
		prop:'remark',
		label:'退费说明'
	}
]

export const tableData = [
	{
		orderNo:'2545asesa5356',
		createdTime:new Date().toLocaleDateString(),
		signUpTime:new Date().toLocaleDateString(),
		carId:'粤B.324366',
		subject:'科目二',
		model:'c2',
		coachName:'教练姓名',
		school:'东莞广仁',
		duration:2,
		coachPhone:'1353695452',
		discount:'无',
		isDelay:'y',
		orderAmt:'200.00',
		payAmt:'200.00',
		refundAmt:'180',
		state:0,
		reason:'时间安排不对',
		remark:'',
		id:'asdfsad'
	}
]
