

export const cars_formModel = [
	{
		group:true,
		label:'驾校筛选',
		elemType:'group',
		childs:[
			{
				elemType:'select',
				label:'所属城市',
				prop:'city',
				defaultValue:'',
				col:'label',
				classes:'noRadiusRight',
				colVal:'value',
				width:109,
				options:[
					{label:'深圳',value:'shenzhen'},
					{label:'东莞',value:'dongguan'},
					{label:'广州',value:'guangzhou'}
				]
			},
			{
				elemType:'select',
				label:'所属驾校',
				prop:'driverSchool',
				defaultValue:'',
				col:'label',
				colVal:'value',
				classes:'noRadiusLeft',
				width:109,
				options:[
					{label:'深港',value:'shenzhen'},
					{label:'广仁',value:'dongguan'},
					{label:'港安',value:'guangzhou'}
				]
			}
		]
	},
	{
		elemType:'select',
		label:'车辆类型',
		prop:'carType',
		defaultValue:'',
		col:'label',
		colVal:'value',
		options:[
			{label:'深港',value:'shenzhen'},
			{label:'广仁',value:'dongguan'},
			{label:'港安',value:'guangzhou'}
		]
	},
	{
		group:true,
		label:'高级搜索',
		elemType:'group',
		childs:[
			{
				elemType:'select',
				label:'请选择......',
				prop:'searchType',
				classes:'noRadiusRight',
				defaultValue:'',
				width:109,
				col:'label',
				colVal:'value',
				options:[
					{label:'教练名称',value:'all'},
					{label:'教练电话',value:'inner'},
					{label:'练考车牌',value:'other'}
				]
			},
			{
				elemType:'input',
				label:'请输入......',
				prop:'content',
				classes:'noRadiusLeft',
				width:109,
				defaultValue:''
			}
		]
	}
]


export const cars_tableModel = [
	
	{
		type:'index',
		width:50
	},
	{
		prop:'names',
		label:'车牌号',
		width:180
	},
	{
		prop:'subjectType',
		label:'车辆类型',
		width:120
	},
	{
		prop:'school',
		label:'所属驾校',
		width:180
	},
	{
		prop:'address',
		label:'教练姓名',
		width:100
	},
	{
		prop:'areas',
		label:'联系方式',
		width:120
	},
	{
		prop:'tel',
		label:'行驶证编号',
		width:200
	},
	{
		prop:'remark',
		label:'备注'
	}
]
