export const states = {
	'0':'待审核',
	'1':'已认证',
	'2':'认证失败'
}

export const formModel = [
	{
		elemType:'select',
		label:'教练属性',
		prop:'coachType',
		defaultValue:'',
		col:'label',
		colVal:'value',
		options:[
			{
				label:'全部',
				value:0
			},
			{
				label:'内部',
				value:1
			},
			{
				label:'外部',
				value:2
			}
		]
	},
	{
		group:true,
		label:'教练来源',
		elemType:'group',
		childs:[
			{
				elemType:'select',
				label:'请选择......',
				prop:'city',
				defaultValue:'',
				col:'label',
				classes:"noRadiusRight",
				colVal:'value',
				width:109,
				options:[
					{label:'深圳',value:'shenzhen'},
					{label:'东莞',value:'dongguan'},
					{label:'广州',value:'guangzhou'}
				]
			},
			{
				elemType:'select',
				label:'请选择......',
				prop:'driverSchool',
				classes:"noRadiusLeft",
				defaultValue:'',
				col:'label',
				colVal:'value',
				width:109,
				options:[
					{label:'深港',value:'shenzhen'},
					{label:'广仁',value:'dongguan'},
					{label:'港安',value:'guangzhou'}
				]
			},
		]
	},
	{
		elemType:'select',
		label:'驾考车型',
		prop:'carType',
		defaultValue:'',
		col:'label',
		colVal:'value',
		options:[
			{
				label:'A1',
				value:'A1'
			},
			{
				label:'B1',
				value:'B1'
			},
			{
				label:'C1',
				value:'C1'
			}
		]
	},
	{
		group:true,
		label:'高级搜索',
		elemType:'group',
		childs:[
			{
				elemType:'select',
				label:'请选择......',
				prop:'searchType',
				defaultValue:'',
				width:109,
				classes:'noRadiusRight',
				col:'label',
				colVal:'value',
				options:[
					{label:'教练名称',value:'all'},
					{label:'教练电话',value:'inner'},
					{label:'练考车牌',value:'other'}
				]
			},
			{
				elemType:'input',
				label:'请输入......',
				prop:'content',
				width:109,
				defaultValue:'',
				classes:'noRadiusLeft'
			}
		]
	}
]


export const tableModel = [
	{
		type:'selection',
		width:50,
		align:'center'
	},{
		type:'index',
		width:50,
		align:'center',
	},{
		label:'申请时间',
	    prop:'applyTime',
	    width:200,
	    align:'center'
	},{
		label:'姓名',
		prop:'coachName',
		align:'center',
		width:100
	},{
		label:'性别',
		prop:'sex',
		align:'center',
		width:'50'
	},{
		label:'所属城市',
		align:'center',
		prop:'city'
	},{
		label:'所属驾校',
		align:'center',
		prop:'school'
	},{
		label:'教练电话',
		prop:'coachPhone',
		align:'center',
		width:150
	},{
		label:'身份证号',
		prop:'idCard',
		align:'center',
		width:180
	},{
		label:'备注',
		align:'center',
		prop:'remark'
	}
]


export const tableData = [
	{
		id:1,
		applyTime:'2017-09-18 11:08:26',
		coachName:'张天易',
		sex:'男',
		city:'深圳',
		school:'深港',
		coachPhone:'13232323232',
		idCard:'42118219881212',
		state:0,
		remark:'证件信息不符合'
	}
]
